# Generated by Django 6.1.1 on 2026-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0002_alter_department_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='normalized_transcript',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64),
        ),
    ]
