# Generated by Django 6.1.1 on 2026-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_apiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
